FactOff/FactOff/Controllers/FactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using FactOff.Models.DB;
using FactOff.Attributes;
using FactOff.Services.Contracts;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using FactOff.Models.ViewModels;

namespace FactOff.Controllers
{
    /// <summary>
    /// Only logged in users can access it.
    /// Responsible for all views in the Facts folder.
    /// </summary>
    [FactOffAuthorize]
    public class FactsController : Controller
    {
        /// <summary>
        /// Allows communication with the <c>FactsService class</c>.
        /// </summary>
        private readonly IFactsService factsService;
        /// <summary>
        /// Allows communication with the <c>TagsService class</c>.
        /// </summary>
        private readonly ITagsService tagsService;
        /// <summary>
        /// Allows communication with the <c>UsersService class</c>.
        /// </summary>
        private readonly IUsersService usersService;
        /// <summary>
        /// Allows communication with the <c>themesService class</c>.
        /// </summary>
        private readonly IThemesService themesService;

        /// <summary>
        /// Initializes a new instance of the FactsController class.
        /// It's being called by the StartUp class.
        /// </summary>
        /// <param name="factsService">A required service for the class.</param>
        /// <param name="tagsService">A required service for the class.</param>
        /// <param name="usersService">A required service for the class.</param>
        public FactsController(IFactsService factsService, ITagsService tagsService, IUsersService usersService, IThemesService themesService)
        {
            this.factsService = factsService;
            this.tagsService = tagsService;
            this.usersService = usersService;
            this.themesService = themesService;
        }

        /// <summary>
        /// The main page with the facts.
        /// Redirects to the Index page in the Facts folder.
        /// </summary>
        /// <returns>Rendered view to the response.</returns>
        public IActionResult Index()
        {
            var model = factsService.GetAllFacts();
            return View(model);
        }
        /// <summary>
        /// Saves the fact to the logged user.
        /// </summary>
        /// <param name="factToSave">Fact that the user wants to save.</param>
        /// <returns>Rendered view to the response.</returns>
        [HttpPost]
        public IActionResult Index(Fact factToSave) {
            Guid userId = new Guid(HttpContext.Session.GetString("logeduser"));
            usersService.SaveFactToUser(usersService.GetUserById(userId), factToSave);
            var model = factsService.GetAllFacts();
            return View(model);
        }

        /// <summary>
        /// Opens the page for creating a new fact.
        /// </summary>
        /// <returns>Rendered view to the response.</returns>
        [FactOffAuthorize]
        public IActionResult Create()
        {
            var model = new CreateFactViewModel() {
                ThemesNames = themesService.GetAllThemes().Select(t => t.Name)
            };
            return View(model);
        }

        /// <summary>
        /// Creates the new fact.
        /// </summary>
        /// <param name="factContext">The context of the new fact.</param>
        /// <param name="tagsString">String with all the tags.</param>
        /// <returns>Rendered view to the response.</returns>
        [HttpPost]
        public IActionResult Create(string factContext, string tagsString, string selectedTheme)
        {
            User user = usersService.GetUserById(new Guid(HttpContext.Session.GetString("logeduser")));
            Guid factId = factsService.CreateFact(factContext, user, selectedTheme);
            IEnumerable<Guid> tagsId = tagsService.CreateTags(tagsString);
            foreach (Guid tagId in tagsId)
            {
                factsService.AddTag(factsService.GetFactById(factId), tagsService.GetTagById(tagId));
            }
            return RedirectToAction("Index");
        }
    }
}

FactOff/FactOff/Views/Shared/PageNotFound.cshtml
@{
    ViewData["Title"] = "PageNotFound";
}

<h1 class="text-danger">404 Page not found.</h1>
<h2 class="text-danger">An error occurred while processing your request.</h2>

FactOff/FactOff/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using FactOff.Services.Contracts
@inject IUsersService userService

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FactOff</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">FactOff</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    @if (string.IsNullOrWhiteSpace(Context.Session.GetString("logeduser")))
                    {
                        <li><a asp-area="" asp-controller="Account" asp-action="SignIn">Sign In</a></li>
                    }
                    else
                    {
                        var userName = userService.GetUserById(new Guid(Context.Session.GetString("logeduser"))).Name;
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@userName <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a asp-area="" asp-controller="Account" asp-action="Profile">My Profile</a></li>
                                <li><a asp-area="" asp-controller="Account" asp-action="EditProfile">Edit Profile</a></li>
                                <li><a asp-area="" asp-controller="Facts" asp-action="Create">Add Fact</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a asp-area="" asp-controller="Account" asp-action="SignOut">Sign Out</a></li>
                            </ul>
                        </li>
                    }
                </ul>
                <form class="navbar-form navbar-right" method="get">
                    <div class="form-group">
                        <input type="text" name="search" class="form-control" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-default" asp-area="" asp-controller="Search" asp-action="Index"><img src="~/images/icons8-search-filled.svg" alt="search" /></button>
                </form>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div class="row">
                <p>&copy; 2019 - FactOff</p>
                <a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
            </div>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>