FactOff/FactOff/Models/ViewModels/HomeViewModel.cs
using System.Collections.Generic;

namespace FactOff.Models.ViewModels
{
    /// <summary>
    /// View Model for the Index page in the Home folder.
    /// </summary>
    public class HomeViewModel
    {
        /// <summary>
        /// A collection of the themes.
        /// </summary>
        public IEnumerable<HomeThemeViewModel> Themes { get; set; }
        /// <summary>
        /// A collection of the facts.
        /// </summary>
        public IEnumerable<HomeFactViewModel> Facts { get; set; }
    }
}

FactOff/FactOff/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using FactOff.Models;
using FactOff.Models.ViewModels;
using FactOff.Services.Contracts;
using System.Linq;
using System.Collections;

namespace FactOff.Controllers
{
    /// <summary>
    /// Responsible for all views in the Home folder.
    /// </summary>
    public class HomeController : Controller
    {
        /// <summary>
        /// Allows communication with the <c>ThemesService class</c>.
        /// </summary>
        private readonly IThemesService themesService;
        /// <summary>
        /// Allows communication with the <c>FactsService class</c>.
        /// </summary>
        private readonly IFactsService factsService;

        /// <summary>
        /// Initializes a new instance of the HomeController class.
        /// It's being called by the StartUp class.
        /// </summary>
        /// <param name="themesService">A required service for the class.</param>
        /// <param name="factsService">A required service for the class.</param>
        public HomeController(IThemesService themesService, IFactsService factsService)
        {
            this.themesService = themesService;
            this.factsService = factsService;
        }

        /// <summary>
        /// The main page. Displays ten rendom facts and some themes.
        /// Redirects to the Index page in the Home folder.
        /// </summary>
        /// <returns>Rendered view to the response.</returns>
        public IActionResult Index()
        {
            var model = new HomeViewModel
            {
                Themes = themesService.GetAllThemes().Select(t => new HomeThemeViewModel
                {
                    ThemeId = t.ThemeId,
                    Name = t.Name
                }),
                Facts = factsService.GetRandomTen().Select(f => new HomeFactViewModel
                {
                    Context = f.Context,
                    Rating = f.Rating,
                    CreatorName = f.Creator.Name,
                    TagsNames = f.Tags.Select(t => t.Tag.Name)
                })
            };
            return View(model);
        }


        /// <summary>
        /// Lets the user contact the developers if he encounters a problem.
        /// Redirect to the Contact page in the Home folder.
        /// </summary>
        /// <returns>Rendered view to the response.</returns>
        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        /// <summary>
        /// Shows the user the privacy policy.
        /// Redirects to the Privacy page in the Home folder.
        /// </summary>
        /// <returns>Rendered view to the response.</returns>
        public IActionResult Privacy()
        {
            return View();
        }

        /// <summary>
        /// If the user tries to reach a page that doesn't exist he is redirected to 404 Page Not Found.
        /// Redirects to the PageNotFound file in the Shared folder.
        /// </summary>
        /// <returns>Rendered view to the response.</returns>
        public IActionResult PageNotFound()
        {
            return RedirectToAction("PageNotFount", "Shared");
        }


        /// <summary>
        /// In case of an error tells the user.
        /// Redirects to the Error page in the Shared folder.
        /// </summary>
        /// <returns>Rendered view to the response.</returns>
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FactOff/FactOff/Controllers/ThemesController.cs
using System;
using System.IO;
using FactOff.Attributes;
using FactOff.Models.ViewModels;
using FactOff.Services.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace FactOff.Controllers
{
    /// <summary>
    /// Only logged in users can access it.
    /// Responsible for all views in the Themes folder.
    /// </summary>
    public class ThemesController : Controller
    {
        /// <summary>
        /// Allows communication wuth the ThemesService class.
        /// </summary>
        private readonly IThemesService service;

        /// <summary>
        /// Initializes a new instance of the ThemesController class.
        /// It's being called by the StartUp class.
        /// </summary>
        /// <param name="service">A required service for the class.</param>
        public ThemesController(IThemesService service)
        {
            this.service = service;
        }

        /// <summary>
        /// Redirects to the Index page in the Themes folder.
        /// </summary>
        /// <returns>Rendered view to the response.</returns>
        [FactOffAuthorize]
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Opens a form for the creation of a new theme.
        /// Redirects to the Create page in the Themes folder.
        /// </summary>
        /// <returns>Rendered view to the response.</returns>
        [FactOffAuthorize]
        public IActionResult Create()
        {
            return View();
        }
        
        /// <summary>
        /// Creates a new theme.
        /// </summary>
        /// <param name="request">The model for the new theme.</param>
        /// <returns></returns>
        [FactOffAuthorize]
        [HttpPost]
        public IActionResult Create(ThemeViewModel request)
        {
            if (ModelState.IsValid)
            {
                byte[] image;
                using (var ms = new MemoryStream())
                {
                    request.ImageUploaded.CopyTo(ms);
                    image = ms.ToArray();
                }
                service.CreateTheme(request.Name, image, request.ImageUploaded.ContentType);
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        /// <summary>
        /// Return the image of the theme given the <paramref name="themeId"/>.
        /// </summary>
        /// <param name="themeId">The id of the theme.</param>
        /// <returns>The image of the theme.</returns>
        public FileStreamResult GetThemeImage(Guid themeId)
        {
            var theme = service.GetThemeById(themeId);
            Stream stream = new MemoryStream(theme.Image);
            return new FileStreamResult(stream, theme.ImageContentType);
        }
    }
}

FactOff/FactOff/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

FactOff/FactOff/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}

<h1 class="centered">Contact us</h1>

<div class="container">

    <form class="form-signin">
        <label for="inputName" class="sr-only">Name</label>
        <input type="text" id="inputName" class="form-control" placeholder="Name" required="">
        <label for="inputEmail" class="sr-only">Email address</label>
        <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required="" autofocus="">
        <label for="inputText" class="sr-only">Text</label>
        <input type="text" id="inputText" class="form-control" placeholder="Text" required="">
        <button class="btn btn-lg btn-primary btn-block" type="submit">Submit</button>
    </form>

</div>

FactOff/FactOff/Views/Home/Index.cshtml
@model HomeViewModel
@{
    ViewData["Title"] = "Home Page";
}

<div>
    <h1 class="centered">
        Want to check out some facts? <br /> Want to waste some precious time? <br /> You are welcome.
    </h1>
</div>

<br />


<div class="row">

    @foreach (var theme in Model.Themes)
    {
        <div class="col-xs-6 col-sm-4 col-md-3">
            <div class="thumbnail">
                <a href="">
                    <div class="box ratio16_9">
                        <div class="content">
                            <img src="@Url.Action("GetThemeImage", "Themes", new {themeId = theme.ThemeId})" alt="Art theme">
                        </div>
                    </div>
                    <div class="caption">
                        <h3 class="centered">@theme.Name</h3>
                    </div>
                </a>
            </div>
        </div>
    }

</div>

@foreach (var fact in Model.Facts)
{
<div class="facts-container">
    <div class="row fact-padding">
        <div>
            <p class="fact-creator">@fact.CreatorName</p>
            @*rating*@
        </div>
        <div>
            <p>@fact.Context</p>
            @foreach (var tagName in fact.TagsNames)
            {
                <span class="tags">@tagName</span>
            }
        </div>
    </div>
</div>
}